### ISSUE TITLE
Remove dependecy on regex package

### ISSUE THREAD

**Issue by bowbahdoe** [jschomay/elm-bounded-number#5]
It seems as if this code puts a dependency on the regex package, but I cannot figure out for what. If there is no reason for it to be a dependency then it should probably be removed so the package is unaffected by changed in said package.

**Comment by jschomay** [comment]
Sorry I didn't see this until now!  It is fixed by #6 and published as 2.1.2 https://package.elm-lang.org/packages/jschomay/elm-bounded-number/2.1.2/
